"""
Canonical locations of the repository's data, figure and media directories.

Scripts live one level down in ``scripts/`` and notebooks two levels down in
``notebooks/<system>/``, so neither can rely on the current working directory
(and a notebook has no ``__file__`` at all). Anything that reads or writes an
artefact imports its directory from here:

    from hhb.paths import KERR_DATA_DIR, CAT_FIG_DIR, MEDIA_DIR

Which of these are tracked by git is deliberate, and is spelled out in
``.gitignore``:

    data/     tracked -- the .npz sweep records are the regression baseline
    figures/cat/  tracked -- paper figures
    figures/kerr/ ignored -- regenerated by the sweep scripts
    media/    ignored -- 84 MB of animations, regenerable from the notebooks
"""

from pathlib import Path


def _find_repo_root() -> Path:
    """Locate the repository root, preferring the source tree this file is in."""
    # Editable install (the normal case): this file is <repo>/src/hhb/paths.py.
    for cand in Path(__file__).resolve().parents:
        if (cand / "pyproject.toml").is_file() and (cand / "src" / "hhb").is_dir():
            return cand

    # Installed as a wheel, with no source tree next to it: fall back to the
    # working directory and its parents.
    cwd = Path.cwd().resolve()
    for cand in (cwd, *cwd.parents):
        if (cand / "pyproject.toml").is_file():
            return cand

    return cwd


REPO_ROOT = _find_repo_root()

DATA_DIR = REPO_ROOT / "data"
KERR_DATA_DIR = DATA_DIR / "kerr"
CAT_DATA_DIR = DATA_DIR / "cat"

FIG_DIR = REPO_ROOT / "figures"
KERR_FIG_DIR = FIG_DIR / "kerr"
CAT_FIG_DIR = FIG_DIR / "cat"

MEDIA_DIR = REPO_ROOT / "media"
