"""
Sweep the Kerr strength chi and compute, for each chi, the period-averaged
Hellinger distance between

  * Q_HBn   : the order-n (Gram-Charlier/Edgeworth-corrected Gaussian) Husimi
              function rebuilt from the harmonic-balance cumulant solution of
              hb_moments_kerr_n.py, and
  * Q_exact : the Husimi function of the truncated-Fock Lindblad steady state
              obtained with dynamiqs.

Q_HBn generalizes the third-order notebook's ansatz:
    Q_n(z) = Q_G(z) * [1 + sum_{3 <= j+k <= n} kappa_jk/(j! k!) * h_jk(z)]
with h_jk = (-d/dZ)^j (-d/dZ*)^k Q_G / Q_G (Wirtinger derivatives, Z = z-mu).
The h_jk are generated by a polynomial recursion (no hand-derived formulas):
    h_{j+1,k} = -(d/dZ  h_jk + g  h_jk),   g  = dlogQ_G/dZ  = (sigt* Z - sig Z*)/D
    h_{j,k+1} = -(d/dZ* h_jk + gb h_jk),   gb = dlogQ_G/dZ* = (-sig Z + sigt Z*)/D
The correction integrates to zero, leaves cumulants of order < each term
intact, and its integrated cumulants reproduce every kappa_jk exactly
(verified by --selftest). Edgeworth tails can dip below zero -- Q_n is
clipped at 0, consistent with the Hellinger integrand.

Usage (from anywhere, once `pip install -e ".[bench]"` has been run):
    python scripts/sweep_kerr_hellinger_n.py --order 3            # full chi sweep
    python scripts/sweep_kerr_hellinger_n.py --order 4 --chi 1.0  # single chi
    python scripts/sweep_kerr_hellinger_n.py --selftest           # Q_n moment check

Results are saved to data/kerr/sweep_kerr_hellinger_n{order}.npz and
figures/kerr/sweep_kerr_hellinger_n{order}.png.
NOTE: the symbolic derivation in hb_moments_kerr_n runs once per process
(~30 s for order 4) and is then reused by every chi in the sweep.
"""

import argparse
from math import factorial

import numpy as np

# Generated artefacts live at the repository root, resolved independently of
# the caller's working directory. data/kerr/*.npz is tracked (it is the
# regression baseline); figures/kerr/ is gitignored.
from hhb.paths import KERR_DATA_DIR as DATA_DIR, KERR_FIG_DIR as FIG_DIR

from hhb.kerr.hb_moments_kerr_n import KerrParams, HBSettingsMomentsN, MomentHillMethodN


# ----------------------------------------------------------------------
# Fixed physical parameters; chi is the swept quantity
# ----------------------------------------------------------------------
Delta = 1.0
kappa = 1.0
eps = 3.0
omega_d = 1.3

CHI_VALUES = np.linspace(0.0, 1.5, 10)

# HB settings
N_H = 14
SAMPLES_PER_HARMONIC = 48

# Fock / dynamiqs settings
N_FOCK = 20
N_PERIODS_TOTAL = 20        # transient + steady state
N_PERIODS_USE = 2           # periods kept for the phase average
N_SAVE = 4000

# phase-space grid for the Hellinger integral
GRID_LIM = 4.0
GRID_PTS = 100


# ----------------------------------------------------------------------
# Order-n Husimi function: Gaussian x Gram-Charlier correction
# ----------------------------------------------------------------------
def _hermite_polys(order, sig, sigt):
    """Polynomial coefficients of h_jk for all j+k <= order.

    Returns {(j,k): {(p,q): coeff}} with h_jk(Z) = sum coeff * Z^p * conj(Z)^q.
    Built by the recursion h_{j+1,k} = -(dZ h + g h), h_{j,k+1} = -(dZ* h + gb h),
    where g = c1 Z + c2 Z*, gb = c2 Z + conj(c1) Z*.
    """
    D = sig**2 - abs(sigt)**2
    c1 = np.conj(sigt) / D
    c2 = -sig / D

    def dP(P, wrt):          # wrt = 0: d/dZ, 1: d/dZ*
        out = {}
        for (p, q), c in P.items():
            if wrt == 0 and p > 0:
                out[(p - 1, q)] = out.get((p - 1, q), 0) + p * c
            if wrt == 1 and q > 0:
                out[(p, q - 1)] = out.get((p, q - 1), 0) + q * c
        return out

    def mul_lin(P, a, b):    # multiply by (a*Z + b*Z*)
        out = {}
        for (p, q), c in P.items():
            out[(p + 1, q)] = out.get((p + 1, q), 0) + a * c
            out[(p, q + 1)] = out.get((p, q + 1), 0) + b * c
        return out

    def add(P1, P2):
        out = dict(P1)
        for k, c in P2.items():
            out[k] = out.get(k, 0) + c
        return out

    def neg(P):
        return {k: -c for k, c in P.items()}

    H = {(0, 0): {(0, 0): 1.0 + 0.0j}}
    for m in range(order):                       # raise total degree
        for j in range(m + 1):
            k = m - j
            P = H[(j, k)]
            if (j + 1, k) not in H:
                H[(j + 1, k)] = neg(add(dP(P, 0), mul_lin(P, c1, c2)))
            if (j, k + 1) not in H:
                H[(j, k + 1)] = neg(add(dP(P, 1), mul_lin(P, c2, np.conj(c1))))
    return H


def Q_hb_grid_n(X, Y, mu, sig, sigt, kappas, order):
    """Order-n Husimi Q.

    kappas: dict {(j,k): complex} for 3 <= j+k <= order, j >= k
    (conjugates kappa_kj are supplied internally). Clipped at 0.
    """
    Z = (X + 1j * Y) - mu
    D = sig**2 - np.abs(sigt)**2
    QG = (1 / np.pi / np.sqrt(D)
          * np.exp((-sig * np.abs(Z)**2 + np.real(np.conj(sigt) * Z**2)) / D))
    if order <= 2:
        return QG

    H = _hermite_polys(order, sig, sigt)
    Zc = np.conj(Z)

    def h_eval(j, k):
        out = np.zeros_like(Z)
        for (p, q), c in H[(j, k)].items():
            out = out + c * Z**p * Zc**q
        return out

    corr = np.zeros(Z.shape)
    for (j, k), kap_jk in kappas.items():
        w = kap_jk / (factorial(j) * factorial(k))
        term = w * h_eval(j, k)
        # kappa_kj h_kj = conj(kappa_jk h_jk) on the real slice
        corr += 2 * np.real(term) if j != k else np.real(term)
    return np.clip(QG * (1 + corr), 0.0, None)


# ----------------------------------------------------------------------
# Exact reference (dynamiqs) and Hellinger machinery
# ----------------------------------------------------------------------
def coherent_overlaps(alpha_grid, n_fock):
    n = np.arange(n_fock)
    log_norm = -0.5 * np.abs(alpha_grid)[:, None]**2 - 0.5 * np.array(
        [np.sum(np.log(np.arange(1, k + 1))) for k in n])[None, :]
    return np.exp(log_norm) * alpha_grid[:, None]**n[None, :]   # (M, n_fock)


def make_Q_exact(C, shape):
    def Q_exact_grid(rho):
        rho = np.asarray(rho)
        Q_flat = np.real(np.einsum('mi,ij,mj->m', C.conj(), rho, C)) / np.pi
        return Q_flat.reshape(shape)
    return Q_exact_grid


def hellinger(Q1, Q2, dA):
    return np.sqrt(max(0.0, 1 - np.sum(np.sqrt(np.clip(Q1 * Q2, 0, None))) * dA))


def make_fourier_interp(samples, T):
    """samples: 1D array (real or complex) uniformly sampled on [0, T)."""
    N = samples.size
    coeffs = np.fft.fft(samples) / N
    freqs = np.fft.fftfreq(N, d=T / N) * 2 * np.pi
    def f_at(t):
        t = np.atleast_1d(t)
        return np.exp(1j * np.outer(t, freqs)) @ coeffs
    return f_at


def solve_exact(chi):
    """Lindblad evolution; returns (T, t_use, states_use)."""
    import dynamiqs as dq
    import jax.numpy as jnp

    dq.set_precision('double')      # required for the 1e-12 tolerances below
    a = dq.destroy(N_FOCK)
    H_0 = Delta * a.dag() @ a + chi / 2 * (a.dag() @ a.dag()) @ (a @ a)
    H_drive_a = dq.modulated(lambda t: eps / 2 * (1 + jnp.exp(-2j * omega_d * t)), a)
    H_drive_a_dag = dq.modulated(lambda t: eps / 2 * (1 + jnp.exp(2j * omega_d * t)), a.dag())
    H_tot = H_0 + H_drive_a + H_drive_a_dag
    jump_op = [jnp.sqrt(kappa) * a]

    T = 2 * np.pi / (2 * omega_d)     # folding period of the drive
    t_max = N_PERIODS_TOTAL * T
    t_save = np.linspace(0, t_max, N_SAVE)

    psi_0 = dq.coherent(N_FOCK, -2)
    method = dq.method.Tsit5(atol=1e-12, rtol=1e-12)
    res = dq.mesolve(H_tot, jump_op, psi_0, t_save, method=method)

    mask = t_save >= t_max - N_PERIODS_USE * T
    idx = np.where(mask)[0]
    return T, t_save[idx], [res.states[i] for i in idx]


# ----------------------------------------------------------------------
# One chi at a time
# ----------------------------------------------------------------------
def solve_hb(order, chi, z_guess=None):
    kerr = KerrParams(Delta=Delta, chi=chi, kappa=kappa, eps=eps, omega_d=omega_d)
    settings = HBSettingsMomentsN(order=order, N_H=N_H,
                                  samples_per_harmonic=SAMPLES_PER_HARMONIC)
    hb = MomentHillMethodN(kerr, settings)
    z_sol = hb.solve(z_guess)       # None -> vacuum guess (continuation otherwise)
    return hb, z_sol


def mean_hellinger_for_chi(order, chi, X, Y, Q_exact_grid, dA, z_guess=None):
    hb, z_sol = solve_hb(order, chi, z_guess)
    rec = hb.reconstruct(z_sol)

    T, t_use, states_use = solve_exact(chi)

    # HB interpolants live on hb.T_fund; evaluating at absolute times is safe.
    interp = {name: make_fourier_interp(np.asarray(rec[name], dtype=complex),
                                        hb.T_fund)(t_use)
              for name in rec if name != 't'}
    mu_t = interp['mu']
    sig_t = np.real(interp['k11'])
    sigt_t = interp['k20']
    kap_names = [(j, k) for (j, k) in
                 [tuple(map(int, name[1:])) for name in rec
                  if name.startswith('k') and name not in ('k11', 'k20')
                  and name not in ('sig2', 'ts2')]
                 if j + k >= 3]

    # Gaussian-part physicality. With n = <da^dag da> = sigma^2 - 1 and
    # m = <da^2>, a single-mode Gaussian state is physical iff n(n+1) >= |m|^2.
    # (sigma^2 >= 1 + |m| is NOT the right bound: it is strictly stronger and
    # reports the exact Lindblad state -- physical by construction -- as
    # unphysical by ~0.11 already at chi = 1/3.)
    n_occ = sig_t - 1.0
    viol = n_occ * (n_occ + 1.0) < np.abs(sigt_t)**2 - 1e-9
    n_viol = int(viol.sum())

    distances = np.empty(len(states_use))
    for k_t, rho_k in enumerate(states_use):
        kappas = {(j, k): interp[f'k{j}{k}'][k_t] for (j, k) in kap_names}
        Q_hb = Q_hb_grid_n(X, Y, mu_t[k_t], sig_t[k_t], sigt_t[k_t],
                           kappas, hb.order)
        distances[k_t] = hellinger(Q_exact_grid(rho_k), Q_hb, dA)

    # fold onto one period and average with the trapezoid rule
    t_mod = t_use % T
    idx = np.argsort(t_mod)
    avg = np.trapezoid(distances[idx], t_mod[idx]) / T

    return avg, distances.max(), n_viol, len(distances), z_sol


def run_sweep(order, chi_values, plot=True):
    real_axis = np.linspace(-GRID_LIM, GRID_LIM, GRID_PTS)
    imag_axis = np.linspace(-GRID_LIM, GRID_LIM, GRID_PTS)
    X, Y = np.meshgrid(real_axis, imag_axis)
    dA = (real_axis[1] - real_axis[0]) * (imag_axis[1] - imag_axis[0])

    C = coherent_overlaps((X + 1j * Y).ravel(), N_FOCK)
    Q_exact_grid = make_Q_exact(C, X.shape)

    avg_list, max_list = [], []
    z_guess = None
    for chi in chi_values:
        avg, dmax, n_viol, n_pts, z_guess = mean_hellinger_for_chi(
            order, chi, X, Y, Q_exact_grid, dA, z_guess
        )
        avg_list.append(avg)
        max_list.append(dmax)
        note = f"  [unphysical at {n_viol}/{n_pts} phases]" if n_viol else ""
        print(f"order {order}  chi = {chi:.4f}   mean Hellinger = {avg:.4f}"
              f"   max = {dmax:.4f}{note}")

    avg_arr, max_arr = np.array(avg_list), np.array(max_list)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    fname = DATA_DIR / f'sweep_kerr_hellinger_n{order}.npz'
    np.savez(fname, chi=np.asarray(chi_values), mean=avg_arr, max=max_arr)
    print(f"saved {fname}")

    if plot and len(chi_values) > 1:
        import matplotlib.pyplot as plt
        plt.figure(figsize=(6.5, 4.5))
        # this order + every other order found on disk: mean (solid) and
        # worst phase (dashed), one color per order
        curves = {order: (np.asarray(chi_values), avg_arr, max_arr)}
        for other in range(2, 7):
            if other == order:
                continue
            try:
                ref = np.load(DATA_DIR / f'sweep_kerr_hellinger_n{other}.npz')
                curves[other] = (ref['chi'], ref['mean'], ref['max'])
            except FileNotFoundError:
                pass
        for i, (o, (c, mean_c, max_c)) in enumerate(sorted(curves.items())):
            plt.plot(c, mean_c, 'o-', color=f'C{i}', label=f'order {o}, period-averaged')
            plt.plot(c, max_c, 's--', color=f'C{i}', alpha=0.6,
                     label=f'order {o}, worst phase')
        plt.xlabel(r'Kerr strength $\chi$')
        plt.ylabel('Hellinger distance')
        plt.title(r'$Q_{\rm HB}$ vs $Q_{\rm exact}$ over one drive period')
        plt.legend(fontsize=8)
        plt.grid(alpha=0.3)
        plt.tight_layout()
        FIG_DIR.mkdir(parents=True, exist_ok=True)
        figname = FIG_DIR / f'sweep_kerr_hellinger_n{order}.png'
        plt.savefig(figname, dpi=150)
        print(f"saved {figname}")
    return avg_arr, max_arr


# ----------------------------------------------------------------------
# Self-test of Q_hb_grid_n: integrated cumulants must reproduce the inputs
# ----------------------------------------------------------------------
def selftest():
    rng_mu, sig = 0.3 - 0.2j, 1.4
    sigt = 0.3 + 0.25j
    kappas = {(3, 0): 0.10 - 0.06j, (2, 1): -0.04 + 0.08j,
              (4, 0): 0.05 + 0.03j, (3, 1): -0.03 - 0.02j, (2, 2): 0.04}

    L, npts = 8.0, 801
    ax = np.linspace(-L, L, npts)
    X, Y = np.meshgrid(ax, ax)
    dA = (ax[1] - ax[0])**2
    # NO clipping here: the identities below hold for the signed density
    Z = (X + 1j * Y) - rng_mu
    D = sig**2 - abs(sigt)**2
    QG = (1 / np.pi / np.sqrt(D)
          * np.exp((-sig * np.abs(Z)**2 + np.real(np.conj(sigt) * Z**2)) / D))
    H = _hermite_polys(4, sig, sigt)
    corr = np.zeros(Z.shape)
    for (j, k), kap_jk in kappas.items():
        h = sum(c * Z**p * np.conj(Z)**q for (p, q), c in H[(j, k)].items())
        w = kap_jk / (factorial(j) * factorial(k))
        corr += 2 * np.real(w * h) if j != k else np.real(w * h)
    Q = QG * (1 + corr)

    def m(j, k):
        return (Q * Z**j * np.conj(Z)**k).sum() * dA

    checks = {
        'norm': (Q.sum() * dA, 1.0),
        'mean shift': (m(1, 0), 0.0),
        'sigma^2 (k11)': (m(1, 1), sig),
        'tilde s^2 (k20)': (m(2, 0), sigt),
        'k30': (m(3, 0), kappas[(3, 0)]),
        'k21': (m(2, 1), kappas[(2, 1)]),
        'k40': (m(4, 0) - 3 * m(2, 0)**2, kappas[(4, 0)]),
        'k31': (m(3, 1) - 3 * m(2, 0) * m(1, 1), kappas[(3, 1)]),
        'k22': (m(2, 2) - m(2, 0) * m(0, 2) - 2 * m(1, 1)**2, kappas[(2, 2)]),
    }
    ok = True
    for name, (got, want) in checks.items():
        err = abs(got - want)
        ok &= err < 1e-8
        print(f"  {name:16s}: got {got:.10f}  want {want}  |err| = {err:.2e}")
    print("selftest", "PASSED" if ok else "FAILED")
    return ok


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument('--order', type=int, default=3,
                    help='cumulant truncation order n (>= 2)')
    ap.add_argument('--chi', type=float, default=None,
                    help='run a single chi instead of the full sweep')
    ap.add_argument('--chi-max', type=float, default=None,
                    help='truncate the sweep at this chi (e.g. before the '
                         'closure stops converging: order 4 fails past ~1.32)')
    ap.add_argument('--selftest', action='store_true',
                    help='verify Q_hb_grid_n cumulants and exit')
    args = ap.parse_args()

    if args.selftest:
        raise SystemExit(0 if selftest() else 1)

    chis = CHI_VALUES if args.chi is None else np.array([args.chi])
    if args.chi_max is not None:
        chis = np.unique(np.append(chis[chis < args.chi_max], args.chi_max))
    run_sweep(args.order, chis)
